name: HTML Lint

on:
  push:
    paths:
      - '**/*.html'
  pull_request:
    paths:
      - '**/*.html'

jobs:
  htmlhint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or any supported version

      - name: Install dependencies
        run: npm install

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"
